#!/usr/bin/env bash

# Pull thirdparty libraries
svn export http://konstrukt.googlecode.com/svn/trunk thirdparty/konstrukt
svn export http://pdoext.googlecode.com/svn/trunk thirdparty/pdoext
svn export http://framework.zend.com/svn/framework/standard/tags/release-1.9.5/library/ thirdparty/zf

wget http://svn.php.net/viewvc/pear2/sandbox/SimpleChannelServer/trunk/pearscs.phar?view=co
mv "pearscs.phar?view=co" script/pearscs.phar
chmod +x script/pearscs.phar

# Set file permissions
chmod 777 log

# create var/channel
pushd www || exit -1
ln -s ../var/channel/get get
ln -s ../var/channel/rest rest
popd
mkdir var/channel
mkdir var/channel/get && chmod 777 var/channel/get
mkdir var/channel/rest && chmod 777 var/channel/rest
